version: "3.8"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234567890
    volumes:
      - ./init/mariadb:/docker-entrypoint-initdb.d
      - ./volumes/mariadb:/var/lib/mariadb
    ports:
      - 3306:3306